### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by pawelklimek** [EpuEpu/where-to-lunch#1]
https://github.com/EpuEpu/where-to-lunch/blob/b14a5e5f5a65581490329b128251ccda1b15fdea/docker-compose.yml#L1

dobrą praktyką jest korzystane z pliku `.env` do zmiennych 

```
COMPETENCE_MYSQL_DATABASE=competence_service_db
COMPETENCE_MYSQL_USER=competence_user
COMPETENCE_MYSQL_PASSWORD=competence_pass
COMPETENCE_MYSQL_ROOT_PASSWORD=competence_pass
COMPETENCE_MYSQL_PORT=3410
```

```
services:
  competence-service-db:
    image: competence-service-db
    build:
      dockerfile: competence-service-db/Dockerfile
      args:
        - MY_DATABASE_NAME=${COMPETENCE_MYSQL_DATABASE}
        - MY_USER=${COMPETENCE_MYSQL_USER}
        - MY_PASSWORD=${COMPETENCE_MYSQL_PASSWORD}
        - MY_ROOT_PASSWORD=${COMPETENCE_MYSQL_ROOT_PASSWORD}
    ports:
      - "${COMPETENCE_MYSQL_PORT}:3306"
```

dobrze tez miec `dockerfile` per service.

<img width="335" alt="image" src="https://github.com/EpuEpu/where-to-lunch/assets/20891862/8a9d4338-1fe3-4eea-807b-38f8c9e635c9">
